FROM fedora:latest

RUN dnf install -y \
    bash \
    git \
    python3 \
    python3-pip \
    nodejs \
    npm \
    wl-clipboard \
    xclip \
    procps-ng \
    curl \
    findutils \
    && dnf clean all

# Criar usuário com mesmo UID (1000)
RUN useradd -m -u 1000 -s /bin/bash jub

USER jub
WORKDIR /workspace

ENV HOME=/home/jub
ENV PATH="/usr/local/bin:${PATH}"
